spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  mail:
    host: ${MAIL_HOST:127.0.0.1}
    port: 587
    username: ${MAIL_USERNAME:test}
    password: ${MAIL_PASSWORD:test}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
server:
  port: ${PORT:8080}
  error:
    include-message: always
db-scheduler:
  enabled: false