spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
server:
  port: ${PORT:8080}
  error:
    include-message: always