name: Backend Quality Analysis

on: [push]

jobs:
  analysis:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres
        ports:
        - 5432:5432
    steps:
    - name: Checkout Backend Repository
      uses: actions/checkout@v3
    - name: Install Java 17
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 17
    - name: Run Sonarcloud Analysis
      uses: gradle/gradle-build-action@v2.1.4
      with:
        arguments: jacocoTestReport sonarqube --info
        cache-disabled: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        MAIL_HOST: ${{ secrets.MAIL_HOST }}
        MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
        MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      if: github.ref_name == 'main'
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        heroku_app_name: "group-matcher-api"