name: Backend Quality Analysis

on: push

jobs:
  gradle:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: 17

    - name: Setup and execute Gradle 'test' task
      uses: gradle/gradle-build-action@v2
      with:
        arguments: test

    - name: Generate Report
      uses: gradle/gradle-build-action@v2
      with:
        arguments: jacocoTestReport

    - name: Quality Analysis
      uses: gradle/gradle-build-action@v2
      with:
        arguments: sonarqube
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
