name: Backend Quality Analysis

on: [push]

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 17

    - name: Generate Report
      uses: gradle/gradle-build-action@v2
      with:
        arguments: jacocoTestReport

    - name: Quality Analysis
      uses: gradle/gradle-build-action@v2
      with:
        arguments: sonarqube
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
