name: Backend Quality Analysis

on: push

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Generate Report
      uses: gradle/gradle-build-action@v2.1.4
      with:
        arguments: jacocoTestReport
        cache-disabled: true
      
    - name: Quality Analysis
      uses: gradle/gradle-build-action@v2.1.4
      with:
        arguments: sonarqube
        cache-disabled: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
